// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3Os5yg-MmRkZNAo5TbZG53QXmrw4BK58',
    appId: '1:893794794335:web:8b883decaaf8d9fc2e94ea',
    messagingSenderId: '893794794335',
    projectId: 'spotify-clone-a72f6',
    authDomain: 'spotify-clone-a72f6.firebaseapp.com',
    storageBucket: 'spotify-clone-a72f6.appspot.com',
    measurementId: 'G-EBZ6CVHCSK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMG7JW0nnl9_0DIm4wj7wXOTHaTBeEMOY',
    appId: '1:893794794335:android:b3856eac19f5b2672e94ea',
    messagingSenderId: '893794794335',
    projectId: 'spotify-clone-a72f6',
    storageBucket: 'spotify-clone-a72f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD56j2ooBEdYPXby0AtKOt715e13EfMqXc',
    appId: '1:893794794335:ios:ad0ef1bb06367b372e94ea',
    messagingSenderId: '893794794335',
    projectId: 'spotify-clone-a72f6',
    storageBucket: 'spotify-clone-a72f6.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD56j2ooBEdYPXby0AtKOt715e13EfMqXc',
    appId: '1:893794794335:ios:ad0ef1bb06367b372e94ea',
    messagingSenderId: '893794794335',
    projectId: 'spotify-clone-a72f6',
    storageBucket: 'spotify-clone-a72f6.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3Os5yg-MmRkZNAo5TbZG53QXmrw4BK58',
    appId: '1:893794794335:web:ba3f92c7ad3ea8822e94ea',
    messagingSenderId: '893794794335',
    projectId: 'spotify-clone-a72f6',
    authDomain: 'spotify-clone-a72f6.firebaseapp.com',
    storageBucket: 'spotify-clone-a72f6.appspot.com',
    measurementId: 'G-8SNTQNNVLT',
  );
}
